tunnel:
  # Interface name
  name: tailscale0
  # Interface MTU
  mtu: 8500
  # Multi-queue
  multi-queue: false
  # IPv4 address
  ipv4: 100.100.100.100
  # IPv6 address
  ipv6: 'fc00::1'
  # Post up script
  #post-up-script: /data/adb/tailscale/scripts/tailscaled.tun.up
  # Pre down script
  #pre-down-script: /data/adb/tailscale/scripts/tailscaled.tun.down

socks5:
  # Socks5 server port
  port: 1099
  # Socks5 server address (ipv4/ipv6)
  address: 127.0.0.1
  # Socks5 UDP relay mode (tcp|udp)
  udp: 'udp'
  # Socks5 handshake using pipeline mode
# pipeline: false
  # Socks5 server username
# username: 'username'
  # Socks5 server password
# password: 'password'
  # Socket mark
  mark: 1099

misc:
   # task stack size (bytes)
#  task-stack-size: 20480
   # connect timeout (ms)
#  connect-timeout: 5000
   # read-write timeout (ms)
#  read-write-timeout: 60000
   # stdout, stderr or file-path
   log-file: stdout
   # debug, info, warn or error
   log-level: debug
   # If present, run as a daemon with this pid file
   #pid-file: /data/adb/tailscale/run/hev-socks5-tunnel.pid
   # If present, set rlimit nofile; else use default value
#  limit-nofile: 65535